export { ErrorPage } from './templates/errorPage/errorPage'
export { NotFoundPage } from './templates/notFoundPage/notFoundPage'
export { Button } from './components/button/Button.tsx'
export { ProductCard } from './components/productСards/ProductCard.tsx'
export { Input } from './components/input/Input.tsx'